Modify for Xray working

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -59,6 +59,10 @@ jobs:
               env:
                     XRAY_CLIENT_ID: ${{ secrets.XRAYCLOUD_CLIENT_ID }}
                     XRAY_CLIENT_SECRET: ${{ secrets.XRAYCLOUD_CLIENT_SECRET }}
-                    
-              run: mvn -B xray:import-results -Dxray.clientId=$XRAY_CLIENT_ID -Dxray.clientSecret=$XRAY_CLIENT_SECRET
+              run: |
+                    if [ -z "$XRAY_CLIENT_ID" ] || [ -z "$XRAY_CLIENT_SECRET" ]; then
+                      echo "ERROR: Xray credentials not found in GitHub secrets"
+                      exit 1
+                    fi
+                    mvn -B xray:import-results -Dxray.clientId="$XRAY_CLIENT_ID" -Dxray.clientSecret="$XRAY_CLIENT_SECRET" -X
               continue-on-error: true
